const router = require('express').Router()
const admin = require('../controllers/adminController')
const auth = require('../middleware/authMiddleware')
const reports = require('../controllers/reportController')
const { requirePermission } = require('../middleware/adminAccess')
router.post('/login', admin.login)
router.get('/me', auth, admin.me)
router.get('/reports', auth, requirePermission('reports:read'), reports.list)
router.get('/reports/export', auth, requirePermission('reports:read'), reports.exportCsv)
router.get('/users', auth, require('../middleware/adminAccess').requirePermission('users:manage'), admin.listUsers)
router.post('/users', auth, require('../middleware/adminAccess').requirePermission('users:manage'), admin.createUser)
router.patch('/users/:id', auth, require('../middleware/adminAccess').requirePermission('users:manage'), admin.updateUser)
module.exports = router
