const router = require('express').Router()
const family = require('../controllers/familyController')
const { authenticateAdmin, requirePermission, requireCommunity } = require('../middleware/adminAccess')
router.post('/', family.createFamily)
router.get('/:id/receipt', family.publicReceipt)
router.get('/:id/pdf', authenticateAdmin, requirePermission('families:read'), requireCommunity, family.adminPdf)
router.get('/', authenticateAdmin, requirePermission('families:read'), (req, res, next) => {
  if (req.get('x-community-id') || req.query.communityId) return requireCommunity(req, res, next)
  next()
}, family.listFamilies)
router.get('/:id', authenticateAdmin, requirePermission('families:read'), requireCommunity, family.getFamily)
router.put('/:id', authenticateAdmin, requirePermission('families:write'), requireCommunity, family.updateFamily)
router.patch('/:id/verification', authenticateAdmin, requirePermission('families:verify'), requireCommunity, family.setVerification)
router.delete('/:id', authenticateAdmin, requirePermission('families:write'), requireCommunity, family.deleteFamily)
module.exports = router
